version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
      python: 3.9
    commands:
      - echo "Installing Serverless Framework"
      - npm install -g serverless
      - echo "Installing Python dependencies"
      - pip install -r requirements.txt
  build:
    commands:
      - echo "Deploying with Serverless Framework"
      - serverless deploy --verbose
artifacts:
  files:
    - "**/*"
