version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - npm install -g serverless
      - pip install -r requirements.txt
  build:
    commands:
      - serverless deploy
artifacts:
  files:
    - "**/*"