service: serverless-python-lambda # NOTE: update this with your service name

frameworkVersion: '4'

provider:
  name: aws
  runtime: python3.12
  iam:
    role:
      name: severless-python-lambda-role
      statements:
        - Effect: 'Allow'
          Resource: '*'
          Action: 'ssm:*'
        - Effect: 'Allow'
          Resource: '*'
          Action: 'dynamodb:BatchGetItem'
        - Effect: 'Allow'
          Resource: '*'        
          Action: 'dynamodb:BatchWriteItem'
        - Effect: 'Allow'
          Resource: '*'
          Action: 'dynamodb:GetItem'
        - Effect: 'Allow'
          Resource: '*'
          Action: 'dynamodb:PutItem'
        - Effect: 'Allow'
          Resource: '*'
          Action: 'dynamodb:Query'
        - Effect: 'Allow'
          Resource: '*'
          Action: 'dynamodb:Scan'
        - Effect: 'Allow'
          Resource: '*'
          Action: 'dynamodb:UpdateItem'
        - Effect: 'Allow'
          Resource: '*'
          Action: 'dynamodb:DeleteItem'
        - Effect: 'Allow'
          Resource: '*'
          Action: 's3:PutObject'
        - Effect: 'Allow'
          Resource: '*'
          Action: 's3:GetObject'
        - Effect: 'Allow'
          Resource: '*'
          Action: 's3:DeleteObject'
        - Effect: 'Allow'
          Resource: '*'
          Action: 'events:PutEvents'
        - Effect: 'Allow'
          Resource: '*'
          Action: 'cloudformation:*'


functions:
  hello:
    handler: handler.hello