Parameters:
  ConnectionArn:
    Description: The CodeConnections ARN for your source repository.
    Type: String
  FullRepositoryId:
    Description: The full repository ID to use with your CodeConnections connection.
    Type: String
  BranchName:
    Description: The branch name to use with your CodeConnections connection.
    Type: String
  CodePipelineName:
    Description: The CodePipeline pipeline name that will build your python source project.
    Type: String
    Default: SimplePythonBuildService
  CICodeBuildSpec:
    Description: The CodeBuild project build spec python configuration
    Type: String
    Default: |
      version: 0.2
      
      phases:
        build:
          commands:
            - echo "Install python dependencies"
            - python -m pip install --upgrade pip
            - if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
            # - echo "Run tests"
            # - python -m pip install flake8 pytest
            # - pytest
  RetentionPolicy:
    Description: Define if you'd like the resource retained or deleted when the
      CloudFormation stack is deleted.
    Type: String
    Default: Delete
    AllowedValues:
      - Delete
      - Retain
Resources:
  CodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
        Version: '2012-10-17'
      Policies:
        - PolicyDocument:
            Statement:
              - Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Effect: Allow
                Resource:
                  - !Sub
                    - arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/${projectName}
                    - projectName:
                        Fn::Join:
                          - '-'
                          - - SimplePythonBuildProject
                            - Fn::Select:
                                - 4
                                - Fn::Split:
                                    - '-'
                                    - Fn::Select:
                                        - 2
                                        - Fn::Split:
                                            - /
                                            - Ref: AWS::StackId
                  - !Sub
                    - arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/${projectName}:*
                    - projectName:
                        Fn::Join:
                          - '-'
                          - - SimplePythonBuildProject
                            - Fn::Select:
                                - 4
                                - Fn::Split:
                                    - '-'
                                    - Fn::Select:
                                        - 2
                                        - Fn::Split:
                                            - /
                                            - Ref: AWS::StackId
              - Action:
                  - codebuild:BatchPutCodeCoverages
                  - codebuild:BatchPutTestCases
                  - codebuild:CreateReport
                  - codebuild:CreateReportGroup
                  - codebuild:UpdateReport
                Effect: Allow
                Resource: !Sub
                  - arn:${AWS::Partition}:codebuild:${AWS::Region}:${AWS::AccountId}:report-group/${projectName}-*
                  - projectName:
                      Fn::Join:
                        - '-'
                        - - SimplePythonBuildProject
                          - Fn::Select:
                              - 4
                              - Fn::Split:
                                  - '-'
                                  - Fn::Select:
                                      - 2
                                      - Fn::Split:
                                          - /
                                          - Ref: AWS::StackId
              - Action:
                  - s3:GetBucket*
                  - s3:GetObject*
                  - s3:List*
                Effect: Allow
                Resource:
                  - !GetAtt CodePipelineArtifactsBucket.Arn
                  - !Sub
                    - ${arn}/*
                    - arn: !GetAtt CodePipelineArtifactsBucket.Arn
            Version: '2012-10-17'
          PolicyName: CodeBuildProjectRoleDefaultPolicy
  CodeBuildDefaultPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
            Effect: Allow
            Resource:
              - !Join
                - ''
                - - !Sub arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/
                  - Fn::Join:
                      - '-'
                      - - SimplePythonBuildProject
                        - Fn::Select:
                            - 4
                            - Fn::Split:
                                - '-'
                                - Fn::Select:
                                    - 2
                                    - Fn::Split:
                                        - /
                                        - Ref: AWS::StackId
                  - ':*'
              - !Join
                - ''
                - - !Sub arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/
                  - Fn::Join:
                      - '-'
                      - - SimplePythonBuildProject
                        - Fn::Select:
                            - 4
                            - Fn::Split:
                                - '-'
                                - Fn::Select:
                                    - 2
                                    - Fn::Split:
                                        - /
                                        - Ref: AWS::StackId
          - Action:
              - codebuild:BatchPutCodeCoverages
              - codebuild:BatchPutTestCases
              - codebuild:CreateReport
              - codebuild:CreateReportGroup
              - codebuild:UpdateReport
            Effect: Allow
            Resource: !Join
              - ''
              - - !Sub arn:${AWS::Partition}:codebuild:${AWS::Region}:${AWS::AccountId}:report-group/
                - Fn::Join:
                    - '-'
                    - - SimplePythonBuildProject
                      - Fn::Select:
                          - 4
                          - Fn::Split:
                              - '-'
                              - Fn::Select:
                                  - 2
                                  - Fn::Split:
                                      - /
                                      - Ref: AWS::StackId
                - '-*'
          - Action:
              - s3:GetBucket*
              - s3:GetObject*
              - s3:List*
            Effect: Allow
            Resource:
              - !GetAtt CodePipelineArtifactsBucket.Arn
              - !Join
                - /
                - - !GetAtt CodePipelineArtifactsBucket.Arn
                  - '*'
        Version: '2012-10-17'
      PolicyName: CodeBuildDefaultPolicy
      Roles:
        - !Ref CodeBuildRole
  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Artifacts:
        Type: NO_ARTIFACTS
      Cache:
        Type: NO_CACHE
      Description: Build python source code
      EncryptionKey: alias/aws/s3
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/amazonlinux2-x86_64-standard:5.0
        ImagePullCredentialsType: CODEBUILD
        PrivilegedMode: false
        Type: LINUX_CONTAINER
      Name:
        Fn::Join:
          - '-'
          - - SimplePythonBuildProject
            - Fn::Select:
                - 4
                - Fn::Split:
                    - '-'
                    - Fn::Select:
                        - 2
                        - Fn::Split:
                            - /
                            - Ref: AWS::StackId
      ServiceRole: !GetAtt CodeBuildRole.Arn
      Source:
        BuildSpec: !Ref CICodeBuildSpec
        Type: NO_SOURCE
  CodePipelineArtifactsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: aws:kms
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
    UpdateReplacePolicy: !Ref RetentionPolicy
    DeletionPolicy: !Ref RetentionPolicy
  CodePipelineArtifactsBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref CodePipelineArtifactsBucket
      PolicyDocument:
        Statement:
          - Action: s3:*
            Condition:
              Bool:
                aws:SecureTransport: 'false'
            Effect: Deny
            Principal:
              AWS: '*'
            Resource:
              - !GetAtt CodePipelineArtifactsBucket.Arn
              - !Join
                - /
                - - !GetAtt CodePipelineArtifactsBucket.Arn
                  - '*'
        Version: '2012-10-17'
  CodePipelineRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: codepipeline.amazonaws.com
        Version: '2012-10-17'
  CodePipelineDefaultPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - s3:Abort*
              - s3:DeleteObject*
              - s3:GetBucket*
              - s3:GetObject*
              - s3:List*
              - s3:PutObject
              - s3:PutObjectLegalHold
              - s3:PutObjectRetention
              - s3:PutObjectTagging
              - s3:PutObjectVersionTagging
            Effect: Allow
            Resource:
              - !GetAtt CodePipelineArtifactsBucket.Arn
              - !Join
                - /
                - - !GetAtt CodePipelineArtifactsBucket.Arn
                  - '*'
          - Action: sts:AssumeRole
            Effect: Allow
            Resource:
              - !GetAtt CodeBuildActionRole.Arn
              - !GetAtt CodeConnectionsActionRole.Arn
          - Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
            Effect: Allow
            Resource:
              - !Sub
                - arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codepipeline/${pipelineName}
                - pipelineName: !Ref CodePipelineName
              - !Sub
                - arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codepipeline/${pipelineName}:*
                - pipelineName: !Ref CodePipelineName
          - Action:
              - inspector-scan:ScanSbom
            Effect: Allow
            Resource: '*'
        Version: '2012-10-17'
      PolicyName: CodePipelineDefaultPolicy
      Roles:
        - !Ref CodePipelineRole
  CodePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      ArtifactStore:
        Location: !Ref CodePipelineArtifactsBucket
        Type: S3
      ExecutionMode: QUEUED
      Name: !Ref CodePipelineName
      PipelineType: V2
      RoleArn: !GetAtt CodePipelineRole.Arn
      Stages:
        - Name: Source
          Actions:
            - Name: CodeConnections
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: CodeStarSourceConnection
                Version: '1'
              Configuration:
                ConnectionArn: !Ref ConnectionArn
                FullRepositoryId: !Ref FullRepositoryId
                BranchName: !Ref BranchName
              OutputArtifacts:
                - Name: SourceOutput
              RoleArn: !GetAtt CodeConnectionsActionRole.Arn
              RunOrder: 1
        - Name: PythonBuild
          BeforeEntry:
            Conditions:
              - Result: FAIL
                Rules:
                  - Name: MyDeploymentWindowRule
                    RuleTypeId:
                      Category: Rule
                      Owner: AWS
                      Provider: DeploymentWindow
                      Version: '1'
                    Configuration:
                      Cron: '* * * * * ? *'
                      TimeZone: 'PST'
          Actions:
            - Name: CI_Python_Build
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: '1'
              Configuration:
                ProjectName:
                  Fn::Join:
                    - '-'
                    - - SimplePythonBuildProject
                      - Fn::Select:
                          - 4
                          - Fn::Split:
                              - '-'
                              - Fn::Select:
                                  - 2
                                  - Fn::Split:
                                      - /
                                      - Ref: AWS::StackId
              InputArtifacts:
                - Name: SourceOutput
              RoleArn: !GetAtt CodeBuildActionRole.Arn
              RunOrder: 1
            - Name: Source_Code_Inspector_Scan
              ActionTypeId:
                Category: Invoke
                Owner: AWS
                Provider: InspectorScan
                Version: '1'
              Configuration:
                InspectorRunMode: SourceCodeScan
                CriticalThreshold: '0'
              InputArtifacts:
                - Name: SourceOutput
              OutputArtifacts:
                - Name: SBOMResult
              RunOrder: 1
    DependsOn:
      - CodePipelineDefaultPolicy
  CodeConnectionsActionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              AWS: !Sub arn:${AWS::Partition}:iam::${AWS::AccountId}:root
        Version: '2012-10-17'
  CodeConnectionsActionDefaultPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action: codestar-connections:UseConnection
            Effect: Allow
            Resource: !Ref ConnectionArn
          - Action:
              - s3:Abort*
              - s3:DeleteObject*
              - s3:GetBucket*
              - s3:GetObject*
              - s3:List*
              - s3:PutObject
              - s3:PutObjectLegalHold
              - s3:PutObjectRetention
              - s3:PutObjectTagging
              - s3:PutObjectVersionTagging
            Effect: Allow
            Resource:
              - !GetAtt CodePipelineArtifactsBucket.Arn
              - !Join
                - /
                - - !GetAtt CodePipelineArtifactsBucket.Arn
                  - '*'
          - Action:
              - s3:PutObjectAcl
              - s3:PutObjectVersionAcl
            Effect: Allow
            Resource: !Join
              - /
              - - !GetAtt CodePipelineArtifactsBucket.Arn
                - '*'
        Version: '2012-10-17'
      PolicyName: CodeConnectionsActionDefaultPolicy
      Roles:
        - !Ref CodeConnectionsActionRole
  CodeBuildActionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              AWS: !Sub arn:${AWS::Partition}:iam::${AWS::AccountId}:root
        Version: '2012-10-17'
  CodeBuildActionDefaultPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - codebuild:BatchGetBuilds
              - codebuild:StartBuild
              - codebuild:StopBuild
            Effect: Allow
            Resource: !GetAtt CodeBuildProject.Arn
        Version: '2012-10-17'
      PolicyName: CodeBuildActionDefaultPolicy
      Roles:
        - !Ref CodeBuildActionRole
