AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: sam app with lambda and layer

Resources:
  LambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: TestAppFunction
      Handler: handler.py
      CodeUri: src/
      Runtime: python3.12
      MemorySize: 3008
      Timeout: 30
      Layers:
        - !Ref LambdaDepLayer
  LambdaDepLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: PandasV2Layer
      Description: Dependencies for sam app
      ContentUri: layer/
      CompatibleRuntimes:
        - python3.12
      RetentionPolicy: Retain
    Metadata:
      BuildMethod: python3.12